services:

  nginx-cache:
    image: ricardopaes/wordpress-nginx-cache:latest

    build:
      context: .

    volumes:
      - nginx-cache-data:/var/cache/nginx

    networks:
      - nginx-network

    environment:
      - WORDPRESS_PROTOCOL=${WORDPRESS_PROTOCOL:-http}
      - WORDPRESS_HOST=${WORDPRESS_HOST:-wordpress}
      - WORDPRESS_PORT=${WORDPRESS_PORT:-80}

    ports:
      - 8099:80

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.wordpress-nginx-cache.rule=Host(`${WORDPRESS_DOMAIN}`)
        - traefik.http.routers.wordpress-nginx-cache.entrypoints=websecure
        - traefik.http.routers.wordpress-nginx-cache.tls.certresolver=letsencryptresolver
        - traefik.http.routers.wordpress-nginx-cache.service=nginx-cache
        - traefik.http.services.wordpress-nginx-cache.loadbalancer.server.port=80
        - traefik.http.services.wordpress-nginx-cache.loadbalancer.passHostHeader=true
        
volumes:
  nginx-cache-data:
    driver: local

networks:
  nginx-network:
    name: ${WORDPRESS_NETWORK}
    external: true