services:

  nginx-cache:
    image: ricardopaes/wordpress-nginx-cache:latest
    build:
      context: .
    volumes:
      - nginx-cache-data:/var/cache/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-cache.rule=Host(`${WP_HOST}`)"
      - "traefik.http.routers.wordpress-cache.entrypoints=websecure"
      - "traefik.http.routers.wordpress-cache.tls.certresolver=myresolver"
      - "traefik.http.services.wordpress-cache.loadbalancer.server.port=80"
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
networks:
  traefik-proxy:
    name: ${WP_NETWORK}
    external: true

volumes:
  nginx-cache-data:
    driver: local