services:
  nginx-cache:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cache:/var/cache/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-cache.rule=Host(`${WP_HOST}`)"
      - "traefik.http.routers.wordpress-cache.entrypoints=websecure"
      - "traefik.http.routers.wordpress-cache.tls.certresolver=myresolver"
      - "traefik.http.services.wordpress-cache.loadbalancer.server.port=80"
    networks:
      - traefik-proxy
  
networks:
  traefik-proxy:
    name: ${WP_NETWORK}
    external: true