services:
  nginx-cache:
    image: nginx:latest
    configs:
      - source: nginx_cache_config
        target: /etc/nginx/nginx.conf
    volumes:
      - nginx-cache-data:/var/cache/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-cache.rule=Host(`${WP_HOST}`)"
      - "traefik.http.routers.wordpress-cache.entrypoints=websecure"
      - "traefik.http.routers.wordpress-cache.tls.certresolver=myresolver"
      - "traefik.http.services.wordpress-cache.loadbalancer.server.port=80"
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
networks:
  traefik-proxy:
    name: ${WP_NETWORK}
    external: true

volumes:
  nginx-cache-data:
    driver: local

configs:
  nginx_cache_config:
    external: false
    content: |
      user  nginx;
      worker_processes  auto;

      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;

      events {
          worker_connections  1024;
      }

      http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;

          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          sendfile        on;
          keepalive_timeout  65;

          gzip  on;
          gzip_vary on;
          gzip_proxied any;
          gzip_comp_level 6;
          gzip_buffers 16 8k;
          gzip_http_version 1.1;
          gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;

          # --- NGINX Cache Configuration ---
          proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=wordpress_cache:10m max_size=1g inactive=60m use_temp_path=off;

          server {
              listen 80;
              server_name _;

              proxy_cache wordpress_cache;
              proxy_cache_key "$scheme$request_method$host$request_uri";
              proxy_cache_valid 200 30m;
              proxy_cache_valid 404 1m;

              # Bypass cache for certain requests (e.g., admin, POST requests)
              proxy_cache_bypass $http_pragma $http_authorization $cookie_wordpress_logged_in;
              proxy_no_cache $http_pragma $http_authorization $cookie_wordpress_logged_in;

              add_header X-Cache-Status $upstream_cache_status;

              location / {
                  proxy_pass http://wordpress_crn1:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_redirect off;
              }

              location ~ /(wp-admin|wp-login.php|wp-cron.php) {
                  proxy_pass http://wordpress_crn1:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_redirect off;
                  proxy_cache_bypass 1;
                  proxy_no_cache 1;
              }
          }
      }