services:

  nginx-cache:
    image: ricardopaes/wordpress-nginx-cache:latest

    volumes:
      - nginx-cache-data:/var/cache/nginx

    networks:
      - nginx-network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.nginx_crn1.rule=Host(`${WORDPRESS_DOMAIN}`)
        - traefik.http.routers.nginx_crn1.entrypoints=websecure
        - traefik.http.routers.nginx_crn1.tls.certresolver=letsencryptresolver
        - traefik.http.routers.nginx_crn1.service=wordpress_crn1
        - traefik.http.services.nginx_crn1.loadbalancer.server.port=80
        - traefik.http.services.nginx_crn1.loadbalancer.passHostHeader=true
        
volumes:
  nginx-cache-data:
    driver: local

networks:
  nginx-network:
    name: ${WORDPRESS_NETWORK}
    external: true